### ISSUE TITLE
Exception after updating Bolt to 3.4

### ISSUE THREAD

**Issue by JarJak** [bobdenotter/bolt-chmodinator#3]
When entering chmodinator from admin menu:

`An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "GET_bolt_extensions_chmodinator_check" as such route does not exist.") in "chmodinator.twig" at line 19.`

**Comment by ankedsgn** [comment]
Yup, same here:

To reproduce:

- Using Bolt 3.4.2
- Install the extension
- Click the 'Chmodinator' menu item 
- TOTAL MAYHEM

`An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "GET_bolt_extensions_chmodinator_check" as such route does not exist.") in "chmodinator.twig" at line 19. `

**Comment by xiaohutai** [comment]
The automatic route name is dependent on what URL is bound to the backend, say we have `/beheer` or `/admin` in `branding/path` in `config.yml`, then `GET_bolt_extensions_chmodinator_check` does not exist, it then becomes:

- `GET_beheer_extensions_chmodinator_check`
- `GET_admin_extensions_chmodinator_check`

Best to bind them with names in [ChmodinatorExtension](https://github.com/bobdenotter/bolt-chmodinator/blob/master/src/ChmodinatorExtension.php#L53-L56).
